In [1]:
#numpy

In [1]:
import arithmatic as t

In [8]:
t.addition(66,66)

AttributeError: module 'arithmatic' has no attribute 'addition'

In [5]:
import numpy as np

In [6]:
l1 = [55,65,45,55,57,63]

In [7]:
l1

[55, 65, 45, 55, 57, 63]

In [8]:
ar1 = np.array(l1)

In [9]:
ar1

array([55, 65, 45, 55, 57, 63])

In [7]:
ar2 = np.array(l1,dtype ='float')

In [8]:
ar2

array([55., 65., 45., 55., 57., 63.])

In [20]:
type(l1)

list

In [21]:
type(ar2)

numpy.ndarray

In [22]:
b2=('a','b','c','d','e','f')

In [23]:
b2

('a', 'b', 'c', 'd', 'e', 'f')

In [24]:
type(b2)

tuple

In [25]:
c1=list(b2)

In [26]:
c1

['a', 'b', 'c', 'd', 'e', 'f']

In [27]:
d1=set(c1)

In [28]:
d1

{'a', 'b', 'c', 'd', 'e', 'f'}

In [29]:
e1=dict(d1)

ValueError: dictionary update sequence element #0 has length 1; 2 is required

In [31]:
a2=np.array(b2)

In [32]:
a2

array(['a', 'b', 'c', 'd', 'e', 'f'], dtype='<U1')

In [33]:
a3=np.array(c1)

In [34]:
a3

array(['a', 'b', 'c', 'd', 'e', 'f'], dtype='<U1')

In [35]:
a4=[[6,7,8,9,10],[0,1,2,3,4,5,6]]

In [36]:
a4

[[6, 7, 8, 9, 10], [0, 1, 2, 3, 4, 5, 6]]

In [38]:
b4=np.array(a4)

C:\Users\Harish\AppData\Local\Temp\ipykernel_8180\1258139882.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  b4=np.array(a4)


In [40]:
dir (list)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [41]:
a4

[[6, 7, 8, 9, 10], [0, 1, 2, 3, 4, 5, 6]]

In [46]:
a4=[ [6, 7, 8, 9, 10,5,'a'], [0, 1, 2, 3, 4, 5] ]


In [43]:
a4

[[6, 7, 8, 9, 10, 5], [0, 1, 2, 3, 4, 5]]

In [60]:
z=np.array(a4)

C:\Users\Harish\AppData\Local\Temp\ipykernel_8180\821029619.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  z=np.array(a4)


In [61]:
z

array([list([6, 7, 8, 9, 10, 5, 'a']), list([0, 1, 2, 3, 4, 5])],
      dtype=object)

In [55]:
c=[['a',1,'b',2],['c',3,'d',4],['e',5,'f',6]]

In [56]:
c

[['a', 1, 'b', 2], ['c', 3, 'd', 4], ['e', 5, 'f', 6]]

In [58]:
q=np.array(c)

In [59]:
q

array([['a', '1', 'b', '2'],
       ['c', '3', 'd', '4'],
       ['e', '5', 'f', '6']], dtype='<U11')

In [65]:
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [67]:
np.arange(0.1,1,0.01)

array([0.1 , 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ,
       0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31,
       0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42,
       0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53,
       0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64,
       0.65, 0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75,
       0.76, 0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86,
       0.87, 0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97,
       0.98, 0.99])

In [68]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [69]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [71]:
np.random.randn(56)

array([-1.06104294,  0.32831167,  0.49309041,  1.13821969, -0.68132707,
        3.21859797,  0.38613738,  0.07180231,  1.5807556 , -1.35377689,
       -0.17386384,  0.27249868,  0.30223733,  0.01095414,  0.64382952,
        1.25012754,  0.8261982 ,  0.88615277, -0.7343539 , -1.06559801,
       -1.42352343, -0.06250419, -0.98472659,  0.22559739, -2.22176515,
        0.55023347,  0.9327494 , -1.38949497, -0.55100493, -0.94838335,
        0.2034655 ,  0.50507038,  0.88469576, -0.70558301,  2.27501238,
        1.33749744, -0.6054016 ,  1.1470127 , -0.50838949, -2.28228524,
        2.06371838, -0.6973163 ,  0.18884394, -1.73842233,  0.95635759,
        0.38146542,  0.39770229,  0.98654705, -0.48054656,  0.30710879,
       -1.17564177,  0.68868773,  0.84364562, -0.81284818,  0.7443134 ,
       -1.69535677])

In [79]:
x=np.eye(6)
x

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [80]:
x*10

array([[10.,  0.,  0.,  0.,  0.,  0.],
       [ 0., 10.,  0.,  0.,  0.,  0.],
       [ 0.,  0., 10.,  0.,  0.,  0.],
       [ 0.,  0.,  0., 10.,  0.,  0.],
       [ 0.,  0.,  0.,  0., 10.,  0.],
       [ 0.,  0.,  0.,  0.,  0., 10.]])

In [81]:
np.random.randint(low=10,high=100,size=15)

array([35, 76, 52, 44, 28, 12, 24, 92, 74, 40, 17, 80, 56, 64, 78])

In [87]:
np.random.seed(45)
np.random.randint(low=55,high=200,size=6)

array([186, 179,  87, 150, 123, 176])

In [88]:
np.random.seed(45)

In [89]:
x1=[np.arange(10)]

In [90]:
x1

[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])]

In [91]:
x1[: :-1]

[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])]

In [92]:
x1[1: :]

[]

In [94]:
x1[1: 2:7]

[]

In [95]:
x1[0:8:2]

[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])]

In [100]:
x1[1::]

[]

In [103]:
x1[-1: :]

[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])]

In [104]:
arr=np.arange(0,10)

In [105]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [111]:
arr1=arr.reshape(5,2)

In [112]:
arr1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [120]:
arr2=np.append(arr,20*arr1)

In [121]:
arr2

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,   0,  20,  40,
        60,  80, 100, 120, 140, 160, 180])

In [122]:
np.concatenate((arr,arr1,arr2))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [123]:
x=np.arange(0,10,2)

In [124]:
x

array([0, 2, 4, 6, 8])

In [125]:
age=np.arange(10)

In [126]:
age

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [127]:
for i in age:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [129]:
num=np.array([[1,3,5],[4,6,8],[7,9,11]])

In [130]:
num

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

In [131]:
for i in num:
    for j in i:
        print(j)

1
3
5
4
6
8
7
9
11


In [132]:
import numpy as np

# Create a 3D array of shape (2, 3, 4)
arr_3d = np.arange(24).reshape(2, 3, 4)
print(arr_3d)


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [133]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [135]:
arr_10d=np.arange(90).reshape(3,10,3)

In [136]:
arr_10d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]],

       [[30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 43, 44],
        [45, 46, 47],
        [48, 49, 50],
        [51, 52, 53],
        [54, 55, 56],
        [57, 58, 59]],

       [[60, 61, 62],
        [63, 64, 65],
        [66, 67, 68],
        [69, 70, 71],
        [72, 73, 74],
        [75, 76, 77],
        [78, 79, 80],
        [81, 82, 83],
        [84, 85, 86],
        [87, 88, 89]]])

In [10]:
import pandas as pd

In [139]:
# pandas, series, dataframe, 

# creating sereis
# list, tuple, dict, numpy array(1d)

In [11]:
l1=['apple',5,'orange',6,'mango',8,'papaya',11,'jack',55,'banana',88]

In [12]:
l1

['apple', 5, 'orange', 6, 'mango', 8, 'papaya', 11, 'jack', 55, 'banana', 88]

In [13]:
a=pd.Series(l1)

In [14]:
a

0      apple
1          5
2     orange
3          6
4      mango
5          8
6     papaya
7         11
8       jack
9         55
10    banana
11        88
dtype: object

In [16]:
pd.DataFrame(a)

0
0    apple
1        5
2   orange
3        6
4    mango
5        8
6   papaya
7       11
8     jack
9       55
10  banana
11      88

In [15]:
for i in range(a):
    print(i)

TypeError: 'Series' object cannot be interpreted as an integer

In [18]:
l2=('tom','jerry','beem','kalia','sensei','uncle')

In [19]:
l2

('tom', 'jerry', 'beem', 'kalia', 'sensei', 'uncle')

In [20]:
b=pd.Series(l2)

In [153]:
b

0       tom
1     jerry
2      beem
3     kalia
4    sensei
5     uncle
dtype: object

In [21]:
for i in range(l2):
    print(i)

TypeError: 'tuple' object cannot be interpreted as an integer

In [156]:
l3={'books':'Tamil','English','Maths','Science','Social','Gk'}

SyntaxError: invalid syntax (447645160.py, line 1)

In [22]:
l1 = [45,32,25,6,48]
s = pd.Series(data=l1,
              index=["S1","S2","S3","S4","S5"])
s

S1    45
S2    32
S3    25
S4     6
S5    48
dtype: int64

In [23]:
l2=[3,6,9,12,15,18,21,24,27,30]

In [24]:
s2=pd.Series(data=l2,
            index=[1,2,3,4,5,6,7,8,9,10])

In [25]:
s2

1      3
2      6
3      9
4     12
5     15
6     18
7     21
8     24
9     27
10    30
dtype: int64

In [161]:
import numpy as np
a1 = np.arange(500,505)
s = pd.Series(data=a1,  # numpy array to sereis
              index=[101,102,103,104,105])
s

101    500
102    501
103    502
104    503
105    504
dtype: int32

In [26]:
z=pd.DataFrame(s)

In [27]:
z

0
S1  45
S2  32
S3  25
S4   6
S5  48

In [164]:
s

101    500
102    501
103    502
104    503
105    504
dtype: int32

In [28]:
tuple(s)

(45, 32, 25, 6, 48)

In [29]:
dict(s)

{'S1': 45, 'S2': 32, 'S3': 25, 'S4': 6, 'S5': 48}

In [30]:
list(s)

[45, 32, 25, 6, 48]

In [31]:
set(s)

{6, 25, 32, 45, 48}

In [32]:
type(s)

pandas.core.series.Series

In [33]:
z

0
S1  45
S2  32
S3  25
S4   6
S5  48

In [171]:
list(z)

[0]

In [172]:
tuple(z)

(0,)

In [173]:
set(z)

{0}

In [174]:
dict(z)

{0: 101    500
 102    501
 103    502
 104    503
 105    504
 Name: 0, dtype: int32}

In [175]:
x=(1,2,3,4,5,6)

In [176]:
x

(1, 2, 3, 4, 5, 6)

In [177]:
y=pd.Series(x)

In [178]:
y

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [179]:
z=pd.DataFrame(y)

In [180]:
z

0
0  1
1  2
2  3
3  4
4  5
5  6

In [182]:
{'books':'Sci','soc'}

SyntaxError: invalid syntax (534641071.py, line 1)

In [184]:
my_dict = dict(name="Bard", age=100)


In [185]:
my_dict

{'name': 'Bard', 'age': 100}

In [186]:
type(my_dict)

dict

In [187]:
d = {"Month" : ["Jan","Feb","Mar","APR","May","Jun"],
    "APPL" : [240,265,222,180,195,205],
    "MST" :   [180,165,192,202,177,102]}
df = pd.DataFrame(d)
df

Month  APPL  MST
0   Jan   240  180
1   Feb   265  165
2   Mar   222  192
3   APR   180  202
4   May   195  177
5   Jun   205  102

In [194]:
b={"cars":['BMW','BENZ','SCORPIO','THAR','JEEP','AUDI'],
  "PRICE IN LAKHS":[55,59,50,65,45,70],
  "colours": ['RED','WHITE','GREEN','BLACK','BLUE','RED']}

In [195]:
b

{'cars': ['BMW', 'BENZ', 'SCORPIO', 'THAR', 'JEEP', 'AUDI'],
 'PRICE IN LAKHS': [55, 59, 50, 65, 45, 70],
 'colours': ['RED', 'WHITE', 'GREEN', 'BLACK', 'BLUE', 'RED']}

In [196]:
z=pd.Series(b)

In [197]:
z

cars              [BMW, BENZ, SCORPIO, THAR, JEEP, AUDI]
PRICE IN LAKHS                  [55, 59, 50, 65, 45, 70]
colours            [RED, WHITE, GREEN, BLACK, BLUE, RED]
dtype: object

In [198]:
y=pd.DataFrame(z)

In [199]:
y

0
cars            [BMW, BENZ, SCORPIO, THAR, JEEP, AUDI]
PRICE IN LAKHS                [55, 59, 50, 65, 45, 70]
colours          [RED, WHITE, GREEN, BLACK, BLUE, RED]

In [202]:
x=pd.DataFrame(y,columns=['Details',0])
print(x)

                Details                                       0
cars                NaN  [BMW, BENZ, SCORPIO, THAR, JEEP, AUDI]
PRICE IN LAKHS      NaN                [55, 59, 50, 65, 45, 70]
colours             NaN   [RED, WHITE, GREEN, BLACK, BLUE, RED]


In [203]:
x

Details                                       0
cars                NaN  [BMW, BENZ, SCORPIO, THAR, JEEP, AUDI]
PRICE IN LAKHS      NaN                [55, 59, 50, 65, 45, 70]
colours             NaN   [RED, WHITE, GREEN, BLACK, BLUE, RED]

In [204]:
x[::]

Details                                       0
cars                NaN  [BMW, BENZ, SCORPIO, THAR, JEEP, AUDI]
PRICE IN LAKHS      NaN                [55, 59, 50, 65, 45, 70]
colours             NaN   [RED, WHITE, GREEN, BLACK, BLUE, RED]

In [205]:
x[: :1]

Details                                       0
cars                NaN  [BMW, BENZ, SCORPIO, THAR, JEEP, AUDI]
PRICE IN LAKHS      NaN                [55, 59, 50, 65, 45, 70]
colours             NaN   [RED, WHITE, GREEN, BLACK, BLUE, RED]

In [206]:
x[2:1:]

Empty DataFrame
Columns: [Details, 0]
Index: []

In [207]:
x[2:]

Details                                      0
colours      NaN  [RED, WHITE, GREEN, BLACK, BLUE, RED]

In [208]:
x[1:]

Details                                      0
PRICE IN LAKHS      NaN               [55, 59, 50, 65, 45, 70]
colours             NaN  [RED, WHITE, GREEN, BLACK, BLUE, RED]

In [209]:
x[0:]

Details                                       0
cars                NaN  [BMW, BENZ, SCORPIO, THAR, JEEP, AUDI]
PRICE IN LAKHS      NaN                [55, 59, 50, 65, 45, 70]
colours             NaN   [RED, WHITE, GREEN, BLACK, BLUE, RED]

In [210]:
x[3:]

Empty DataFrame
Columns: [Details, 0]
Index: []

In [211]:
x[1:1:]

Empty DataFrame
Columns: [Details, 0]
Index: []

In [212]:
x[1::]

Details                                      0
PRICE IN LAKHS      NaN               [55, 59, 50, 65, 45, 70]
colours             NaN  [RED, WHITE, GREEN, BLACK, BLUE, RED]

In [215]:
x[1:2:1]

Details                         0
PRICE IN LAKHS      NaN  [55, 59, 50, 65, 45, 70]

In [216]:
x.iloc[1]

Details                         NaN
0          [55, 59, 50, 65, 45, 70]
Name: PRICE IN LAKHS, dtype: object

In [217]:
z

cars              [BMW, BENZ, SCORPIO, THAR, JEEP, AUDI]
PRICE IN LAKHS                  [55, 59, 50, 65, 45, 70]
colours            [RED, WHITE, GREEN, BLACK, BLUE, RED]
dtype: object

In [218]:
a

0      apple
1          5
2     orange
3          6
4      mango
5          8
6     papaya
7         11
8       jack
9         55
10    banana
11        88
dtype: object

In [220]:
a.iloc[7]

11

In [222]:
a.loc[5]

8

In [223]:
b

{'cars': ['BMW', 'BENZ', 'SCORPIO', 'THAR', 'JEEP', 'AUDI'],
 'PRICE IN LAKHS': [55, 59, 50, 65, 45, 70],
 'colours': ['RED', 'WHITE', 'GREEN', 'BLACK', 'BLUE', 'RED']}

In [224]:
l1

[45, 32, 25, 6, 48]

In [225]:
l1.iloc[3]

AttributeError: 'list' object has no attribute 'iloc'

In [226]:
y

0
cars            [BMW, BENZ, SCORPIO, THAR, JEEP, AUDI]
PRICE IN LAKHS                [55, 59, 50, 65, 45, 70]
colours          [RED, WHITE, GREEN, BLACK, BLUE, RED]

In [227]:
d

{'Month': ['Jan', 'Feb', 'Mar', 'APR', 'May', 'Jun'],
 'APPL': [240, 265, 222, 180, 195, 205],
 'MST': [180, 165, 192, 202, 177, 102]}

In [228]:
df

Month  APPL  MST
0   Jan   240  180
1   Feb   265  165
2   Mar   222  192
3   APR   180  202
4   May   195  177
5   Jun   205  102

In [229]:
df.iloc[3,2]

202

In [230]:
df.loc[1:2:3]

Month  APPL  MST
1   Feb   265  165

In [247]:
df.iloc[5:]

Month  APPL  MST
5   Jun   205  102

In [249]:
df.loc[2:]

Month  APPL  MST
2   Mar   222  192
3   APR   180  202
4   May   195  177
5   Jun   205  102

In [251]:
df.iloc[2:]

Month  APPL  MST
2   Mar   222  192
3   APR   180  202
4   May   195  177
5   Jun   205  102

In [253]:
import seaborn as sns

In [254]:
sns.pairplot(df)

In [255]:
d1 = {"S1" : 45,
     "S2" : 32,
     "s3" : 26}
pd.Series(d1)

S1    45
S2    32
s3    26
dtype: int64

In [257]:
d2 = {"s1":55,
     "s2":61,
     "s3":66,
     "s4":62,
     "s5":66,
     "s6":59}

In [258]:
d2

{'s1': 55, 's2': 61, 's3': 66, 's4': 62, 's5': 66, 's6': 59}

In [264]:
pd.DataFrame(d2,index=0,5,)

SyntaxError: positional argument follows keyword argument (600749226.py, line 1)

In [265]:
d2

{'s1': 55, 's2': 61, 's3': 66, 's4': 62, 's5': 66, 's6': 59}

In [267]:
q=pd.Series(data=d2)

In [268]:
q

s1    55
s2    61
s3    66
s4    62
s5    66
s6    59
dtype: int64

In [269]:
pd.DataFrame(q)

0
s1  55
s2  61
s3  66
s4  62
s5  66
s6  59

In [272]:
l1 = [  ["Aman", "CHN", "DSE", 43, 34],
     ["Rahul", "BLR", "DSE", 24,44],
     ["Shiva", "BLR","DSE", 33,26],
      ["John", "CHN","AIML", 24,6],
      ["mOHAN", "MUM","DSBA", 8,55]
     ]
pd.DataFrame(l1)

0    1     2   3   4
0   Aman  CHN   DSE  43  34
1  Rahul  BLR   DSE  24  44
2  Shiva  BLR   DSE  33  26
3   John  CHN  AIML  24   6
4  mOHAN  MUM  DSBA   8  55

In [273]:
df = pd.DataFrame(l1,
                  index=["D101","D102","D103","A101","DS101"],
                  columns = ["Name","City","Course","ITP","NPV"])
df

Name City Course  ITP  NPV
D101    Aman  CHN    DSE   43   34
D102   Rahul  BLR    DSE   24   44
D103   Shiva  BLR    DSE   33   26
A101    John  CHN   AIML   24    6
DS101  mOHAN  MUM   DSBA    8   55

In [274]:
df.value_counts

<bound method DataFrame.value_counts of         Name City Course  ITP  NPV
D101    Aman  CHN    DSE   43   34
D102   Rahul  BLR    DSE   24   44
D103   Shiva  BLR    DSE   33   26
A101    John  CHN   AIML   24    6
DS101  mOHAN  MUM   DSBA    8   55>

In [275]:
df.values

array([['Aman', 'CHN', 'DSE', 43, 34],
       ['Rahul', 'BLR', 'DSE', 24, 44],
       ['Shiva', 'BLR', 'DSE', 33, 26],
       ['John', 'CHN', 'AIML', 24, 6],
       ['mOHAN', 'MUM', 'DSBA', 8, 55]], dtype=object)

In [276]:
df.index

Index(['D101', 'D102', 'D103', 'A101', 'DS101'], dtype='object')

In [277]:
df.columns

Index(['Name', 'City', 'Course', 'ITP', 'NPV'], dtype='object')

In [278]:
df.iloc[0:3]

Name City Course  ITP  NPV
D101   Aman  CHN    DSE   43   34
D102  Rahul  BLR    DSE   24   44
D103  Shiva  BLR    DSE   33   26

In [289]:
df.iloc[:5:]

Name City Course  ITP  NPV
D101    Aman  CHN    DSE   43   34
D102   Rahul  BLR    DSE   24   44
D103   Shiva  BLR    DSE   33   26
A101    John  CHN   AIML   24    6
DS101  mOHAN  MUM   DSBA    8   55

In [295]:
df.groupby(by ='Name')["ITP"].mean()

Name
Aman     43.0
John     24.0
Rahul    24.0
Shiva    33.0
mOHAN     8.0
Name: ITP, dtype: float64

In [ ]:
#df.groupby(by="day")["total_bill"].mean()

In [ ]:
#df.groupby(by="day")[["total_bill"]].aggregate(["min","max","mean"])

In [296]:
df.groupby(by ='Name')["ITP"].aggregate(["min","max","mean"])

min  max  mean
Name                 
Aman    43   43  43.0
John    24   24  24.0
Rahul   24   24  24.0
Shiva   33   33  33.0
mOHAN    8    8   8.0

In [297]:
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

# Create a random 2D array
data = np.random.rand(5, 5)

# Create a heatmap
sns.heatmap(data, cmap='YlGnBu')

# Display the plot
plt.show()


In [298]:
df

Name City Course  ITP  NPV
D101    Aman  CHN    DSE   43   34
D102   Rahul  BLR    DSE   24   44
D103   Shiva  BLR    DSE   33   26
A101    John  CHN   AIML   24    6
DS101  mOHAN  MUM   DSBA    8   55

In [10]:
a={'subject':'Tamil'}

In [17]:
b=dict(a)

In [19]:
type(a)

dict

In [26]:
c=pd.Series(a)

In [21]:
import pandas as pd

In [27]:
c

subject    Tamil
dtype: object

In [28]:
pd.DataFrame(c)

0
subject  Tamil

In [29]:
a

{'subject': 'Tamil'}

In [30]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [38]:
car_shop = {
       'Names':['BMW','AUDI','BENZ','JEEP','LAMBORGHINI','PORSCHE'],
        'COST IN LAKHS' : [63 ,64,65,66,68,69],
       'Colours':["RED","WHITE","BLACK","SANDAL","BLUE","ASH"]
}

cs=pd.Series(car_shop)
cs

Names            [BMW, AUDI, BENZ, JEEP, LAMBORGHINI, PORSCHE]
COST IN LAKHS                         [63, 64, 65, 66, 68, 69]
Colours                 [RED, WHITE, BLACK, SANDAL, BLUE, ASH]
dtype: object

In [42]:
cc=pd.DataFrame(car_shop)
cc

Names  COST IN LAKHS Colours
0          BMW             63     RED
1         AUDI             64   WHITE
2         BENZ             65   BLACK
3         JEEP             66  SANDAL
4  LAMBORGHINI             68    BLUE
5      PORSCHE             69     ASH

In [40]:
df_1=pd.DataFrame(cs)
df_1

0
Names          [BMW, AUDI, BENZ, JEEP, LAMBORGHINI, PORSCHE]
COST IN LAKHS                       [63, 64, 65, 66, 68, 69]
Colours               [RED, WHITE, BLACK, SANDAL, BLUE, ASH]

In [31]:
import pandas as pd

data = {
    'Product': ['Soap', 'Shampoo', 'Conditioner', 'Sanitizer', 'Handwash', 'Bodywash'],
    'Cost(per_unit)': [25, 175, 234, 100, 98, 150],
    'QuantityAvailable': [12, 24, 9, 2, 19, 6]
}

df = pd.DataFrame(data)
print(df)


       Product  Cost(per_unit)  QuantityAvailable
0         Soap              25                 12
1      Shampoo             175                 24
2  Conditioner             234                  9
3    Sanitizer             100                  2
4     Handwash              98                 19
5     Bodywash             150                  6


In [32]:
df

Product  Cost(per_unit)  QuantityAvailable
0         Soap              25                 12
1      Shampoo             175                 24
2  Conditioner             234                  9
3    Sanitizer             100                  2
4     Handwash              98                 19
5     Bodywash             150                  6

In [44]:
df=sns.load_dataset('iris')

In [45]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [46]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [48]:
df['species'].value_counts()

setosa        50
versicolor    50
virginica     50
Name: species, dtype: int64

In [49]:
df['sepal_length'].value_counts(normalize=True)

5.0    0.066667
5.1    0.060000
6.3    0.060000
5.7    0.053333
6.7    0.053333
5.8    0.046667
5.5    0.046667
6.4    0.046667
4.9    0.040000
5.4    0.040000
6.1    0.040000
6.0    0.040000
5.6    0.040000
4.8    0.033333
6.5    0.033333
6.2    0.026667
7.7    0.026667
6.9    0.026667
4.6    0.026667
5.2    0.026667
5.9    0.020000
4.4    0.020000
7.2    0.020000
6.8    0.020000
6.6    0.013333
4.7    0.013333
7.6    0.006667
7.4    0.006667
7.3    0.006667
7.0    0.006667
7.1    0.006667
5.3    0.006667
4.3    0.006667
4.5    0.006667
7.9    0.006667
Name: sepal_length, dtype: float64

In [55]:
pd.pivot_table(data=df,values='sepal_length',aggfunc=['min','max','mean','median'])

ValueError: No group keys passed!

In [56]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [58]:
df.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000